name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - name: checkout code 
      uses: actions/checkout@v2 # Adds a step to checkout the repository code
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: '5.0.x'
    - run: dotnet build 
    - run: dotnet test
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
      with: 
        node-version: '14'
    - run: npm install
    working-directory: ./DotnetTemplate.Web
    - run: npm run build
    working-directory: ./DotnetTemplate.Web
    - run: npm run lint 
    working-directory: ./DotnetTemplate.Web
    - run: npm run test
    working-directory: ./DotnetTemplate.Web
    